#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 2 1 1 "$@"

python $BASEDIR/third.py $INPUTS1 $INPUTS2 $PARAMS1 $OUTPUTS1

checkExitCode.
